import 'package:flutter/material.dart';

class KycProfileScreen extends StatefulWidget { const KycProfileScreen({super.key}); @override State<KycProfileScreen> createState()=>_KycProfileScreenState(); }
class _KycProfileScreenState extends State<KycProfileScreen>{
 final pan=TextEditingController(), pehchan=TextEditingController(), gst=TextEditingController(), ifsc=TextEditingController(), account=TextEditingController(); String gi='Not selected';
 double get readiness { var n=0; if(pan.text.trim().isNotEmpty)n++; if(pehchan.text.trim().isNotEmpty)n++; if(ifsc.text.trim().isNotEmpty&&account.text.trim().isNotEmpty)n++; if(gst.text.trim().isNotEmpty)n++; return n/4; }
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('KYC Profile')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[SizedBox(width:82,height:82,child:CircularProgressIndicator(value:readiness,strokeWidth:9)),const SizedBox(width:18),Expanded(child:Text('GeM Readiness: ${(readiness*100).round()}%\n${readiness<1?'Complete the missing documents':'Profile ready for review'}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)))]))),const SizedBox(height:12),_field(pehchan,'Pehchan ID / Artisan Card Number'),_field(pan,'PAN'),_field(gst,'GSTIN / Udyam'),_field(account,'Bank Account Number'),_field(ifsc,'IFSC Code'),DropdownButtonFormField<String>(initialValue:gi,decoration:const InputDecoration(labelText:'GI Tag'),items:['Not selected','Chanderi Silk','Dhokra Art','Madhubani Painting'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>gi=v??gi)),const SizedBox(height:12),FilledButton.icon(onPressed:(){},icon:const Icon(Icons.document_scanner),label:const Text('Scan document with camera'))]));
 Widget _field(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:x,onChanged:(_)=>setState((){}),decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));
 @override void dispose(){for(final x in [pan,pehchan,gst,ifsc,account])x.dispose();super.dispose();}
}
